# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #    service_name:
    #        class: App\Directory\ClassName
    #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ###########
    # Fixtures #
    ##########
    App\DataFixtures\DataProvider\PasswordHasherProvider:
        tags: [ { name: nelmio_alice.faker.provider } ]